import * as Components from "../componetns"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <title>IziQ-Study</title>
    </head>

      <body>
        <Components.Navigation />
        <h1>Esto aparece en todas las pages</h1>
        {children}
      </body>
    </html>
  )
}
